name: lkf_monorepo

packages:
  - apps/**
  - packages/**

scripts:
  gen:
    exec: dart run build_runner build --delete-conflicting-outputs && flutter gen-l10n
    description: Generating assets from packages
