name: lkf_monorepo

environment:
  sdk: ">=3.2.0 <4.0.0"

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  melos: ^6.1.0
dependencies:
  flutter_localizations:
    sdk: flutter
  intl: any
