name: translations_module
description: translastions package
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0
  flutter: ^3.22.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.0.0
  intl: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  intl_utils: ^2.6.0
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter_intl:
  enabled: true
