name: linkaform_access_control
description: Access control project by Linkaform.
version: 1.0.0+1
publish_to: none
environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  flutter_gen: ^5.6.0
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.4.9
  intl: any
  ui_look_and_feel_module:
    path: "../../packages/ui_look_and_feel_module"

dev_dependencies:
  build_runner: ^2.4.11
  flutter_gen_runner: ^5.6.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
